### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by SBA-Yone** [SBA-Yone/furima-40954#20]
#URL
https://furima-40954.onrender.com

**Comment by motomuun** [comment]
ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**ユーザー管理機能の確認**

- [ ] **パスワードは、半角英数字混合での入力が必須であること**
パスワード入力欄に「aaa11１」※最後の１のみ全角数字　と入力してもエラーメッセージが表示されません。
パスワードに全角数字が一つでも存在する場合はエラーメッセージが表示されるように修正をお願いします。

**商品出品機能の確認**

- [ ] **発送元の地域は、「---」と47都道府県の合計48項目が表示されること（--- は初期値として設定すること）**
 デフォルト値が「--」となっています。実装要件と揃えるため「---」に修正をお願いします。
<img width="323" alt="スクリーンショット 2024-10-29 9 51 59" src="https://github.com/user-attachments/assets/9e58be3a-690d-4e48-8c7c-a3413a37c5f8">

- [ ] **発送までの日数は、「---、1〜2日で発送、2〜3日で発送、4〜7日で発送」の4項目が表示されること（--- は初期値として設定すること）**
「2〜3日で発送」が「3〜4日で発送」になっています。こちらも修正をお願いします。
<img width="327" alt="スクリーンショット 2024-10-29 9 54 17" src="https://github.com/user-attachments/assets/a2f801dd-26ca-4ce2-bad1-14c8caa95e97">



修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう。
修正内容が反映されていることが確認できましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by SBA-Yone** [comment]
確認いただきありがとうございます。
ご指摘いただきました点を修正いたしましたので、
ご確認くださいますようお願いいたします。
https://furima-40954.onrender.com

**Comment by ushi10** [comment]
最終課題「FURIMA」の開発、お疲れ様です。

ご修正、ご提出いただいたアプリケーションについて、正常に動作することを確認いたしました。
達成要件を満たしましたので、完了認定（LGTM）とさせていただきます。おめでとうございます。

_※ スタッフ側で実施した動作確認は必須機能についてのみです。追加機能についての動作確認は実施しておりません。追加機能を実装した場合は想定通りの挙動となっているか自分自身で確認をお願い致します。_
_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)

**Comment by SBA-Yone** [comment]
ご確認いただきありがとうございます。
開発に苦労した分、完成した達成感はひとしおです。
残り日数も少ないですが、追加実装のカリキュラム確認など、できることを進めていきます。
